# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170315_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='''13 Character\n
                                   <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>''',
                                   max_length=13, verbose_name='ISBN'),
        ),
    ]
