# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170316_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='''13 Character\n
                                   <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>''',
                                   max_length=13, verbose_name='ISBN'),
        ),
    ]
